// GENERATED by scripts/sync-shared.mjs from packages/shared/src — do not edit.
import type { AiAnalysis, AiItem, AiLabel, MealPlan } from '../schemas/ai.ts';
import { normalizeText } from '../text.ts';

/**
 * Deterministic AI fixtures used in demo mode (app: EXPO_PUBLIC_USE_MOCKS, server: AI_MOCK) and
 * tests. Realistic Argentine dishes so store reviewers and testers see the full flow.
 */
const item = (
  name: string,
  name_en: string,
  grams: number,
  measure: string,
  method: AiItem['cooking_method'],
  confidence: number,
  per: [number, number, number, number, number?],
  hints: string[],
): AiItem => ({
  name,
  name_en,
  estimated_grams: grams,
  household_measure: measure,
  cooking_method: method,
  confidence,
  per_100g_estimate: {
    kcal: per[0],
    protein_g: per[1],
    carbs_g: per[2],
    fat_g: per[3],
    fiber_g: per[4] ?? 0,
  },
  search_hints: hints,
});

export const MOCK_PLATES: readonly AiAnalysis[] = [
  {
    is_food: true,
    dish_name: 'Milanesa con puré',
    items: [
      item(
        'Milanesa de carne frita',
        'breaded fried beef cutlet',
        160,
        '1 unidad mediana',
        'fried',
        0.82,
        [245, 18, 12, 14, 0.6],
        ['milanesa de carne frita', 'breaded beef cutlet'],
      ),
      item(
        'Puré de papa',
        'mashed potatoes',
        200,
        '1 porción',
        'boiled',
        0.74,
        [105, 2, 15, 4, 1.4],
        ['puré de papa', 'mashed potatoes'],
      ),
    ],
    hidden_ingredients_question: '¿La milanesa fue frita o al horno?',
    notes: 'Porción de puré estimada por el tamaño del plato.',
  },
  {
    is_food: true,
    dish_name: 'Empanadas de carne',
    items: [
      item(
        'Empanada de carne al horno',
        'baked beef empanada',
        240,
        '2 unidades',
        'baked',
        0.86,
        [255, 10, 25, 12.5, 1.5],
        ['empanada de carne al horno', 'beef empanada'],
      ),
    ],
    hidden_ingredients_question: null,
    notes: null,
  },
  {
    is_food: true,
    dish_name: 'Ensalada con pollo',
    items: [
      item(
        'Pechuga de pollo a la plancha',
        'grilled chicken breast',
        150,
        '1 unidad',
        'grilled',
        0.8,
        [165, 31, 0, 3.6],
        ['pechuga de pollo a la plancha', 'grilled chicken breast'],
      ),
      item(
        'Ensalada mixta',
        'mixed green salad',
        180,
        '1 bowl',
        'raw',
        0.7,
        [20, 1, 4, 0.2, 1.5],
        ['ensalada mixta', 'mixed salad'],
      ),
      item(
        'Palta',
        'avocado',
        50,
        '1/4 unidad',
        'raw',
        0.55,
        [160, 2, 8.5, 14.7, 6.7],
        ['palta', 'avocado'],
      ),
    ],
    hidden_ingredients_question: '¿Le pusiste aceite o aderezo a la ensalada?',
    notes: null,
  },
  {
    is_food: true,
    dish_name: 'Fideos con tuco',
    items: [
      item(
        'Tallarines con tuco',
        'spaghetti with meat tomato sauce',
        320,
        '1 plato',
        'boiled',
        0.78,
        [140, 5, 24, 2.5, 1.8],
        ['tallarines con tuco', 'spaghetti tomato sauce'],
      ),
      item(
        'Queso rallado',
        'grated parmesan cheese',
        10,
        '1 cucharada',
        'raw',
        0.5,
        [400, 33, 3, 28.5],
        ['queso rallado', 'grated parmesan'],
      ),
    ],
    hidden_ingredients_question: null,
    notes: null,
  },
];

const TEXT_DICTIONARY: { keys: string[]; item: AiItem; unitGrams: number }[] = [
  {
    keys: ['empanada'],
    unitGrams: 120,
    item: item(
      'Empanada de carne',
      'beef empanada',
      120,
      '1 unidad',
      'baked',
      0.8,
      [255, 10, 25, 12.5, 1.5],
      ['empanada de carne'],
    ),
  },
  {
    keys: ['milanesa'],
    unitGrams: 150,
    item: item(
      'Milanesa de carne',
      'breaded beef cutlet',
      150,
      '1 unidad',
      'fried',
      0.75,
      [270, 18, 14, 16, 0.8],
      ['milanesa de carne frita'],
    ),
  },
  {
    keys: ['coca zero', 'zero', 'light'],
    unitGrams: 354,
    item: item(
      'Gaseosa cola zero',
      'diet cola',
      354,
      '1 lata',
      'raw',
      0.9,
      [0.3, 0, 0, 0],
      ['gaseosa zero'],
    ),
  },
  {
    keys: ['coca', 'gaseosa'],
    unitGrams: 354,
    item: item(
      'Gaseosa cola',
      'cola soda',
      354,
      '1 lata',
      'raw',
      0.85,
      [42, 0, 10.6, 0],
      ['gaseosa cola'],
    ),
  },
  {
    keys: ['medialuna'],
    unitGrams: 40,
    item: item(
      'Medialuna de manteca',
      'butter croissant',
      40,
      '1 unidad',
      'baked',
      0.85,
      [410, 7.5, 47, 21, 1.5],
      ['medialuna de manteca'],
    ),
  },
  {
    keys: ['cafe con leche'],
    unitGrams: 250,
    item: item(
      'Café con leche',
      'coffee with milk',
      250,
      '1 taza',
      'raw',
      0.85,
      [33, 1.7, 2.5, 1.7],
      ['cafe con leche'],
    ),
  },
  {
    keys: ['pure'],
    unitGrams: 200,
    item: item(
      'Puré de papa',
      'mashed potatoes',
      200,
      '1 porción',
      'boiled',
      0.7,
      [105, 2, 15, 4, 1.4],
      ['pure de papa'],
    ),
  },
  {
    keys: ['manzana'],
    unitGrams: 180,
    item: item(
      'Manzana',
      'apple',
      180,
      '1 unidad mediana',
      'raw',
      0.9,
      [52, 0.3, 13.8, 0.2, 2.4],
      ['manzana'],
    ),
  },
  {
    keys: ['banana'],
    unitGrams: 120,
    item: item(
      'Banana',
      'banana',
      120,
      '1 unidad',
      'raw',
      0.9,
      [89, 1.1, 22.8, 0.3, 2.6],
      ['banana'],
    ),
  },
  {
    keys: ['fideo', 'tallarin'],
    unitGrams: 300,
    item: item(
      'Fideos con tuco',
      'spaghetti with tomato sauce',
      300,
      '1 plato',
      'boiled',
      0.7,
      [140, 5, 24, 2.5, 1.8],
      ['tallarines con tuco'],
    ),
  },
  {
    keys: ['huevo'],
    unitGrams: 50,
    item: item(
      'Huevo duro',
      'hard-boiled egg',
      50,
      '1 unidad',
      'boiled',
      0.8,
      [155, 12.6, 1.1, 10.6],
      ['huevo duro'],
    ),
  },
];

const NUMBER_WORDS: Record<string, number> = {
  un: 1,
  una: 1,
  uno: 1,
  dos: 2,
  tres: 3,
  cuatro: 4,
  cinco: 5,
  a: 1,
  one: 1,
  two: 2,
  three: 3,
};

function hash(s: string): number {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) >>> 0;
  return h;
}

export function mockAnalyzeImage(seed: string): AiAnalysis {
  return MOCK_PLATES[hash(seed) % MOCK_PLATES.length]!;
}

/** Very small text parser for demo mode: "dos empanadas y una coca zero". */
export function mockAnalyzeText(text: string): AiAnalysis {
  const norm = normalizeText(text);
  const parts = norm
    .split(/ y | con |,| and /)
    .map((p) => p.trim())
    .filter(Boolean);
  const items: AiItem[] = [];
  for (const part of parts) {
    const entry = TEXT_DICTIONARY.find((d) => d.keys.some((k) => part.includes(k)));
    if (!entry) continue;
    const words = part.split(' ');
    const qty = Number(words.find((w) => /^\d+$/.test(w))) || NUMBER_WORDS[words[0] ?? ''] || 1;
    items.push({
      ...entry.item,
      estimated_grams: entry.unitGrams * qty,
      household_measure:
        qty > 1 ? `${qty} × ${entry.item.household_measure}` : entry.item.household_measure,
    });
  }
  return {
    is_food: items.length > 0,
    dish_name: null,
    items,
    hidden_ingredients_question: null,
    notes: items.length ? null : 'Demo: no reconocimos alimentos en el texto.',
  };
}

export function mockReadLabel(): AiLabel {
  return {
    is_label: true,
    product_name: 'Galletitas de agua',
    brand: null,
    serving_size_g: 30,
    per_100g: {
      kcal: 420,
      protein_g: 10,
      carbs_g: 70,
      fat_g: 11,
      fiber_g: 2.5,
      sugar_g: 2,
      sodium_mg: 700,
      sat_fat_g: 4.5,
    },
    per_serving: {
      kcal: 126,
      protein_g: 3,
      carbs_g: 21,
      fat_g: 3.3,
      fiber_g: 0.8,
      sugar_g: 0.6,
      sodium_mg: 210,
      sat_fat_g: 1.4,
    },
    notes: 'Demo: etiqueta simulada.',
  };
}

export function mockCoachReply(question: string): string {
  return `(Demo) Buena pregunta: "${question.slice(0, 80)}". Una idea simple: sumá una porción de proteína magra (pollo, huevos, legumbres o yogur) y verduras para completar tus macros de hoy. Recordá que esto es información general y no reemplaza a un profesional.`;
}

type MockDish = MealPlan['days'][number]['meals'][number];

const dish = (
  meal_type: MockDish['meal_type'],
  name: string,
  description: string,
  kcal: number,
  protein_g: number,
  carbs_g: number,
  fat_g: number,
): MockDish => ({ meal_type, name, description, kcal, protein_g, carbs_g, fat_g });

const MOCK_DISHES: Record<'breakfast' | 'lunch' | 'snack' | 'dinner', MockDish[]> = {
  breakfast: [
    dish(
      'breakfast',
      'Yogur con avena y banana',
      'Yogur natural, 3 cdas de avena y media banana.',
      350,
      15,
      55,
      8,
    ),
    dish(
      'breakfast',
      'Tostadas con palta y huevo',
      '2 tostadas integrales, ¼ palta y 1 huevo.',
      380,
      17,
      35,
      18,
    ),
    dish(
      'breakfast',
      'Café con leche y medialuna',
      'Café con leche descremada y una medialuna.',
      320,
      11,
      42,
      12,
    ),
    dish(
      'breakfast',
      'Licuado de frutilla y avena',
      'Leche, frutillas, avena y una cdita de miel.',
      340,
      14,
      58,
      6,
    ),
  ],
  lunch: [
    dish(
      'lunch',
      'Pollo con arroz y ensalada',
      'Pechuga a la plancha, 1 taza de arroz y ensalada mixta.',
      600,
      45,
      65,
      15,
    ),
    dish(
      'lunch',
      'Milanesa al horno con puré',
      'Milanesa de carne al horno y puré de calabaza.',
      620,
      40,
      55,
      22,
    ),
    dish(
      'lunch',
      'Guiso de lentejas',
      'Lentejas con verduras y un poco de chorizo colorado.',
      580,
      30,
      75,
      16,
    ),
    dish(
      'lunch',
      'Fideos con tuco y queso',
      'Fideos con salsa de tomate casera y queso rallado.',
      610,
      24,
      95,
      14,
    ),
  ],
  snack: [
    dish(
      'snack',
      'Mate con tostadas y queso',
      '2 tostadas integrales con queso untable light.',
      250,
      12,
      30,
      8,
    ),
    dish('snack', 'Fruta y un puñado de nueces', 'Una manzana y 20 g de nueces.', 230, 5, 25, 13),
    dish('snack', 'Yogur con granola', 'Yogur bebible y 2 cdas de granola.', 240, 9, 38, 6),
  ],
  dinner: [
    dish(
      'dinner',
      'Tarta de verdura y ensalada',
      'Una porción de tarta de acelga con ensalada de tomate.',
      550,
      22,
      45,
      28,
    ),
    dish(
      'dinner',
      'Merluza con papas al horno',
      'Filet de merluza y papas al horno con romero.',
      520,
      38,
      50,
      16,
    ),
    dish(
      'dinner',
      'Wok de carne y verduras',
      'Carne en tiras con vegetales salteados y arroz.',
      560,
      38,
      52,
      20,
    ),
    dish(
      'dinner',
      'Omelette con ensalada',
      'Omelette de 2 huevos con queso y ensalada verde.',
      450,
      28,
      12,
      30,
    ),
  ],
};

const words = (v: string | undefined) =>
  (v ?? '')
    .toLowerCase()
    .split(/[,;\n]+|\sy\s/)
    .map((w) => w.trim())
    .filter((w) => w.length >= 3);

/**
 * Demo meal plan: rotates regional dishes, honours meals per day, skips dishes that mention
 * something the user wants to avoid and favours the ones mentioning what they like.
 */
export function mockMealPlan(
  days: number,
  preferences?: { liked?: string; disliked?: string; mealsPerDay?: number },
): MealPlan {
  const liked = words(preferences?.liked);
  const avoid = words(preferences?.disliked);
  const text = (d: MockDish) => `${d.name} ${d.description}`.toLowerCase();
  const slots: (keyof typeof MOCK_DISHES)[] =
    (preferences?.mealsPerDay ?? 4) <= 3
      ? ['breakfast', 'lunch', 'dinner']
      : ['breakfast', 'lunch', 'snack', 'dinner'];
  const options = (slot: keyof typeof MOCK_DISHES) => {
    const ok = MOCK_DISHES[slot].filter((d) => !avoid.some((w) => text(d).includes(w)));
    const pool = ok.length ? ok : MOCK_DISHES[slot];
    return [...pool].sort(
      (a, b) =>
        Number(liked.some((w) => text(b).includes(w))) -
        Number(liked.some((w) => text(a).includes(w))),
    );
  };
  return {
    days: Array.from({ length: days }, (_, i) => ({
      day: i + 1,
      meals: slots.map((slot) => {
        const pool = options(slot);
        return pool[i % pool.length]!;
      }),
    })),
    shopping_list: [
      { item: 'Pechuga de pollo', quantity: '1 kg', category: 'Carnes' },
      { item: 'Carne picada o nalga', quantity: '700 g', category: 'Carnes' },
      { item: 'Merluza', quantity: '500 g', category: 'Pescados' },
      { item: 'Huevos', quantity: '1 docena', category: 'Lácteos y huevos' },
      { item: 'Yogur natural', quantity: '7 unidades', category: 'Lácteos y huevos' },
      { item: 'Avena', quantity: '500 g', category: 'Almacén' },
      { item: 'Lentejas', quantity: '500 g', category: 'Almacén' },
      { item: 'Acelga', quantity: '2 atados', category: 'Verdulería' },
      { item: 'Tomates', quantity: '1 kg', category: 'Verdulería' },
      { item: 'Bananas y manzanas', quantity: '1 kg', category: 'Verdulería' },
    ],
    notes:
      liked.length || avoid.length
        ? 'Plan de demostración armado con tus preferencias (en la versión real lo genera la IA).'
        : 'Plan de demostración (en la versión real lo genera la IA según tus objetivos y gustos).',
  };
}
