// GENERATED by scripts/sync-shared.mjs from packages/shared/src — do not edit.
import { ADAPTIVE, KCAL_PER_KG_BODY_WEIGHT, SAFETY } from '../constants.ts';
import { diffDays } from '../dates.ts';
import type { Sex } from '../schemas/enums.ts';
import type { DayIntake } from './safeguards.ts';
import { weightTrend, type WeightEntry } from './weight.ts';

export interface AdaptiveInput {
  intakes: readonly DayIntake[];
  weights: readonly WeightEntry[];
  /** Planned signed weekly change (kg/week, negative = loss). */
  plannedWeeklyChangeKg: number;
  currentTargetKcal: number;
  previousTdeeEstimate?: number | null;
  sex: Sex;
  bmr: number;
}

export type AdaptiveResult =
  | {
      status: 'insufficient_data';
      loggedDays: number;
      weighIns: number;
      windowDays: number;
    }
  | {
      status: 'ok';
      observedTdee: number;
      estimatedTdee: number;
      avgIntakeKcal: number;
      trendChangeKg: number;
      windowDays: number;
      newTargetKcal: number;
      deltaKcal: number;
      clamped: boolean;
      floorApplied: boolean;
    };

/**
 * Adaptive energy expenditure (MacroFactor-style):
 *   observed TDEE = average intake − (trend weight change × 7700 kcal/kg) / days
 * The observation is blended with the previous estimate, and the new target moves at most
 * ±150 kcal per weekly check-in. Calorie floors still apply.
 */
export function computeAdaptiveTarget(input: AdaptiveInput): AdaptiveResult {
  const logged = input.intakes.filter((d) => d.mealCount > 0);
  const trend = weightTrend(input.weights);
  const dates = [...logged.map((d) => d.date), ...trend.map((t) => t.date)].sort();
  const windowDays = dates.length ? diffDays(dates[0]!, dates[dates.length - 1]!) + 1 : 0;

  if (
    logged.length < ADAPTIVE.minLoggedDays ||
    trend.length < ADAPTIVE.minWeighIns ||
    windowDays < ADAPTIVE.minWindowDays
  ) {
    return {
      status: 'insufficient_data',
      loggedDays: logged.length,
      weighIns: trend.length,
      windowDays,
    };
  }

  const avgIntake = logged.reduce((s, d) => s + d.kcal, 0) / logged.length;
  const first = trend[0]!;
  const last = trend[trend.length - 1]!;
  const trendDays = Math.max(1, diffDays(first.date, last.date));
  const trendChangeKg = last.trendKg - first.trendKg;
  const observedTdee = avgIntake - (trendChangeKg * KCAL_PER_KG_BODY_WEIGHT) / trendDays;

  const prev = input.previousTdeeEstimate;
  const estimatedTdee =
    prev != null && prev > 0
      ? prev * (1 - ADAPTIVE.blendNewWeight) + observedTdee * ADAPTIVE.blendNewWeight
      : observedTdee;

  let target = estimatedTdee + (input.plannedWeeklyChangeKg * KCAL_PER_KG_BODY_WEIGHT) / 7;
  let clamped = false;
  const maxDelta = ADAPTIVE.maxWeeklyChangeKcal;
  if (target - input.currentTargetKcal > maxDelta) {
    target = input.currentTargetKcal + maxDelta;
    clamped = true;
  } else if (input.currentTargetKcal - target > maxDelta) {
    target = input.currentTargetKcal - maxDelta;
    clamped = true;
  }
  let floorApplied = false;
  const floor = SAFETY.calorieFloor[input.sex];
  if (target < floor) {
    target = floor;
    floorApplied = true;
  }
  const newTargetKcal = Math.round(target / 10) * 10;

  return {
    status: 'ok',
    observedTdee: Math.round(observedTdee),
    estimatedTdee: Math.round(estimatedTdee),
    avgIntakeKcal: Math.round(avgIntake),
    trendChangeKg: Math.round(trendChangeKg * 100) / 100,
    windowDays,
    newTargetKcal,
    deltaKcal: newTargetKcal - input.currentTargetKcal,
    clamped,
    floorApplied,
  };
}
