// GENERATED by scripts/sync-shared.mjs from packages/shared/src — do not edit.
import { SAFETY } from '../constants.ts';

export interface DayIntake {
  date: string;
  kcal: number;
  /** Number of meals logged that day. Days with 0 meals are considered "not logged". */
  mealCount: number;
}

/**
 * Detects sustained extreme restriction: within the window, enough logged days whose
 * average intake is under the threshold. Used only to show a kind, supportive message
 * with professional-help resources — never to shame.
 */
export function detectRestrictionPattern(days: readonly DayIntake[]): boolean {
  const recent = [...days]
    .sort((a, b) => (a.date < b.date ? 1 : -1))
    .slice(0, SAFETY.restrictionWindowDays)
    .filter((d) => d.mealCount > 0);
  if (recent.length < SAFETY.restrictionMinLoggedDays) return false;
  const avg = recent.reduce((s, d) => s + d.kcal, 0) / recent.length;
  return avg < SAFETY.restrictionKcalThreshold;
}

export function isAgeAllowed(ageYears: number): boolean {
  return ageYears >= SAFETY.minAge && ageYears <= SAFETY.maxAge;
}
