// GENERATED by scripts/sync-shared.mjs from packages/shared/src — do not edit.
import { WEIGHT_TREND } from '../constants.ts';
import { diffDays, type IsoDate } from '../dates.ts';

export interface WeightEntry {
  date: IsoDate;
  weightKg: number;
}

export interface TrendPoint extends WeightEntry {
  trendKg: number;
}

/** One entry per day (last value wins), sorted ascending. */
export function dedupeDaily(entries: readonly WeightEntry[]): WeightEntry[] {
  const map = new Map<string, number>();
  for (const e of [...entries].sort((a, b) => (a.date < b.date ? -1 : 1))) {
    map.set(e.date, e.weightKg);
  }
  return [...map.entries()].map(([date, weightKg]) => ({ date, weightKg }));
}

/**
 * Exponentially smoothed trend line (Hacker's Diet style). Gaps between weigh-ins are handled
 * by applying the smoothing factor once per elapsed day.
 */
export function weightTrend(
  entries: readonly WeightEntry[],
  alpha: number = WEIGHT_TREND.emaAlpha,
): TrendPoint[] {
  const sorted = dedupeDaily(entries);
  const out: TrendPoint[] = [];
  let trend: number | null = null;
  let prevDate: string | null = null;
  for (const e of sorted) {
    if (trend == null || prevDate == null) {
      trend = e.weightKg;
    } else {
      const days = Math.max(1, diffDays(prevDate, e.date));
      const effectiveAlpha = 1 - (1 - alpha) ** days;
      trend = trend + effectiveAlpha * (e.weightKg - trend);
    }
    prevDate = e.date;
    out.push({ ...e, trendKg: Math.round(trend * 100) / 100 });
  }
  return out;
}

/** Simple trailing moving average over N calendar days. */
export function movingAverage(
  entries: readonly WeightEntry[],
  days: number = WEIGHT_TREND.movingAverageDays,
): TrendPoint[] {
  const sorted = dedupeDaily(entries);
  return sorted.map((e) => {
    const window = sorted.filter((x) => x.date <= e.date && diffDays(x.date, e.date) < days);
    const avg = window.reduce((s, x) => s + x.weightKg, 0) / window.length;
    return { ...e, trendKg: Math.round(avg * 100) / 100 };
  });
}

/** Least-squares slope of the trend in kg/week. Returns null with < 2 points. */
export function weeklyRateKg(points: readonly TrendPoint[]): number | null {
  if (points.length < 2) return null;
  const first = points[0]!.date;
  const xs = points.map((p) => diffDays(first, p.date));
  const ys = points.map((p) => p.trendKg);
  const n = xs.length;
  const mx = xs.reduce((a, b) => a + b, 0) / n;
  const my = ys.reduce((a, b) => a + b, 0) / n;
  let num = 0;
  let den = 0;
  for (let i = 0; i < n; i++) {
    num += (xs[i]! - mx) * (ys[i]! - my);
    den += (xs[i]! - mx) ** 2;
  }
  if (den === 0) return null;
  return (num / den) * 7;
}

/** Projects the date when `targetKg` would be reached at the given weekly rate. */
export function projectGoalDate(
  currentKg: number,
  targetKg: number,
  ratePerWeekKg: number,
  from: Date,
): string | null {
  const delta = targetKg - currentKg;
  if (ratePerWeekKg === 0 || Math.sign(delta) !== Math.sign(ratePerWeekKg)) return null;
  const weeks = delta / ratePerWeekKg;
  if (weeks > 520) return null;
  return new Date(from.getTime() + weeks * 7 * 86_400_000).toISOString().slice(0, 10);
}
