// GENERATED by `pnpm gen:types` (supabase gen types typescript). Do not edit.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      achievements: {
        Row: {
          achievement_id: string;
          unlocked_at: string;
          user_id: string;
        };
        Insert: {
          achievement_id: string;
          unlocked_at?: string;
          user_id: string;
        };
        Update: {
          achievement_id?: string;
          unlocked_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      ai_feedback: {
        Row: {
          comment: string | null;
          corrected: Json | null;
          created_at: string;
          id: string;
          original: NonNullable<Json>;
          scan_id: string | null;
          user_id: string;
        };
        Insert: {
          comment?: string | null;
          corrected?: Json | null;
          created_at?: string;
          id?: string;
          original: NonNullable<Json>;
          scan_id?: string | null;
          user_id: string;
        };
        Update: {
          comment?: string | null;
          corrected?: Json | null;
          created_at?: string;
          id?: string;
          original?: NonNullable<Json>;
          scan_id?: string | null;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'ai_feedback_scan_id_fkey';
            columns: ['scan_id'];
            isOneToOne: false;
            referencedRelation: 'ai_scans';
            referencedColumns: ['id'];
          },
        ];
      };
      ai_scans: {
        Row: {
          cost_usd: number;
          created_at: string;
          error: string | null;
          id: string;
          image_sha256: string | null;
          input_tokens: number;
          kind: string;
          latency_ms: number | null;
          model: string | null;
          output_tokens: number;
          result: Json | null;
          status: string;
          user_id: string | null;
        };
        Insert: {
          cost_usd?: number;
          created_at?: string;
          error?: string | null;
          id?: string;
          image_sha256?: string | null;
          input_tokens?: number;
          kind: string;
          latency_ms?: number | null;
          model?: string | null;
          output_tokens?: number;
          result?: Json | null;
          status: string;
          user_id?: string | null;
        };
        Update: {
          cost_usd?: number;
          created_at?: string;
          error?: string | null;
          id?: string;
          image_sha256?: string | null;
          input_tokens?: number;
          kind?: string;
          latency_ms?: number | null;
          model?: string | null;
          output_tokens?: number;
          result?: Json | null;
          status?: string;
          user_id?: string | null;
        };
        Relationships: [];
      };
      audit_events: {
        Row: {
          created_at: string;
          event: string;
          id: number;
          metadata: NonNullable<Json>;
          user_id: string | null;
        };
        Insert: {
          created_at?: string;
          event: string;
          id?: never;
          metadata?: NonNullable<Json>;
          user_id?: string | null;
        };
        Update: {
          created_at?: string;
          event?: string;
          id?: never;
          metadata?: NonNullable<Json>;
          user_id?: string | null;
        };
        Relationships: [];
      };
      body_measurements: {
        Row: {
          body_fat_pct: number | null;
          chest_cm: number | null;
          created_at: string;
          deleted_at: string | null;
          hip_cm: number | null;
          id: string;
          local_date: string;
          measured_at: string;
          photo_path: string | null;
          updated_at: string;
          user_id: string;
          waist_cm: number | null;
        };
        Insert: {
          body_fat_pct?: number | null;
          chest_cm?: number | null;
          created_at?: string;
          deleted_at?: string | null;
          hip_cm?: number | null;
          id?: string;
          local_date: string;
          measured_at: string;
          photo_path?: string | null;
          updated_at?: string;
          user_id: string;
          waist_cm?: number | null;
        };
        Update: {
          body_fat_pct?: number | null;
          chest_cm?: number | null;
          created_at?: string;
          deleted_at?: string | null;
          hip_cm?: number | null;
          id?: string;
          local_date?: string;
          measured_at?: string;
          photo_path?: string | null;
          updated_at?: string;
          user_id?: string;
          waist_cm?: number | null;
        };
        Relationships: [];
      };
      favorites: {
        Row: {
          created_at: string;
          deleted_at: string | null;
          id: string;
          kind: string;
          label: string;
          payload: NonNullable<Json>;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          deleted_at?: string | null;
          id?: string;
          kind: string;
          label: string;
          payload: NonNullable<Json>;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          deleted_at?: string | null;
          id?: string;
          kind?: string;
          label?: string;
          payload?: NonNullable<Json>;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      food_cache: {
        Row: {
          cache_key: string;
          fetched_at: string;
          payload: NonNullable<Json>;
          source: string;
        };
        Insert: {
          cache_key: string;
          fetched_at?: string;
          payload: NonNullable<Json>;
          source: string;
        };
        Update: {
          cache_key?: string;
          fetched_at?: string;
          payload?: NonNullable<Json>;
          source?: string;
        };
        Relationships: [];
      };
      foods_custom: {
        Row: {
          barcode: string | null;
          brand: string | null;
          carbs_g: number;
          created_at: string;
          deleted_at: string | null;
          fat_g: number;
          fiber_g: number | null;
          id: string;
          kcal: number;
          micros: NonNullable<Json>;
          name: string;
          origin: string;
          protein_g: number;
          sat_fat_g: number | null;
          servings: NonNullable<Json>;
          sodium_mg: number | null;
          sugar_g: number | null;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          barcode?: string | null;
          brand?: string | null;
          carbs_g?: number;
          created_at?: string;
          deleted_at?: string | null;
          fat_g?: number;
          fiber_g?: number | null;
          id?: string;
          kcal: number;
          micros?: NonNullable<Json>;
          name: string;
          origin?: string;
          protein_g?: number;
          sat_fat_g?: number | null;
          servings?: NonNullable<Json>;
          sodium_mg?: number | null;
          sugar_g?: number | null;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          barcode?: string | null;
          brand?: string | null;
          carbs_g?: number;
          created_at?: string;
          deleted_at?: string | null;
          fat_g?: number;
          fiber_g?: number | null;
          id?: string;
          kcal?: number;
          micros?: NonNullable<Json>;
          name?: string;
          origin?: string;
          protein_g?: number;
          sat_fat_g?: number | null;
          servings?: NonNullable<Json>;
          sodium_mg?: number | null;
          sugar_g?: number | null;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      foods_regional: {
        Row: {
          aliases: string[];
          carbs_g: number;
          category: string;
          countries: string[];
          created_at: string;
          fat_g: number;
          fiber_g: number | null;
          id: string;
          kcal: number;
          micros: NonNullable<Json>;
          name_en: string;
          name_es: string;
          name_pt: string;
          protein_g: number;
          sat_fat_g: number | null;
          servings: NonNullable<Json>;
          sodium_mg: number | null;
          source: string;
          sugar_g: number | null;
        };
        Insert: {
          aliases?: string[];
          carbs_g: number;
          category: string;
          countries?: string[];
          created_at?: string;
          fat_g: number;
          fiber_g?: number | null;
          id: string;
          kcal: number;
          micros?: NonNullable<Json>;
          name_en: string;
          name_es: string;
          name_pt: string;
          protein_g: number;
          sat_fat_g?: number | null;
          servings?: NonNullable<Json>;
          sodium_mg?: number | null;
          source: string;
          sugar_g?: number | null;
        };
        Update: {
          aliases?: string[];
          carbs_g?: number;
          category?: string;
          countries?: string[];
          created_at?: string;
          fat_g?: number;
          fiber_g?: number | null;
          id?: string;
          kcal?: number;
          micros?: NonNullable<Json>;
          name_en?: string;
          name_es?: string;
          name_pt?: string;
          protein_g?: number;
          sat_fat_g?: number | null;
          servings?: NonNullable<Json>;
          sodium_mg?: number | null;
          source?: string;
          sugar_g?: number | null;
        };
        Relationships: [];
      };
      goals: {
        Row: {
          carbs_g: number;
          created_at: string;
          deleted_at: string | null;
          effective_from: string;
          fat_g: number;
          fiber_g: number | null;
          id: string;
          kcal: number;
          mode: string;
          protein_g: number;
          tdee_estimate: number | null;
          updated_at: string;
          user_id: string;
          water_ml: number | null;
        };
        Insert: {
          carbs_g: number;
          created_at?: string;
          deleted_at?: string | null;
          effective_from: string;
          fat_g: number;
          fiber_g?: number | null;
          id?: string;
          kcal: number;
          mode?: string;
          protein_g: number;
          tdee_estimate?: number | null;
          updated_at?: string;
          user_id: string;
          water_ml?: number | null;
        };
        Update: {
          carbs_g?: number;
          created_at?: string;
          deleted_at?: string | null;
          effective_from?: string;
          fat_g?: number;
          fiber_g?: number | null;
          id?: string;
          kcal?: number;
          mode?: string;
          protein_g?: number;
          tdee_estimate?: number | null;
          updated_at?: string;
          user_id?: string;
          water_ml?: number | null;
        };
        Relationships: [];
      };
      meal_items: {
        Row: {
          ai_confidence: number | null;
          carbs_g: number;
          cooking_method: string | null;
          created_at: string;
          display_name: string;
          fat_g: number;
          fiber_g: number | null;
          food_id: string | null;
          food_source: string;
          grams: number;
          id: string;
          kcal: number;
          meal_id: string;
          micros: NonNullable<Json>;
          per100g: NonNullable<Json>;
          position: number;
          protein_g: number;
          sat_fat_g: number | null;
          serving_qty: number | null;
          serving_unit: string | null;
          sodium_mg: number | null;
          sugar_g: number | null;
          updated_at: string;
          user_edited: boolean;
          user_id: string;
        };
        Insert: {
          ai_confidence?: number | null;
          carbs_g?: number;
          cooking_method?: string | null;
          created_at?: string;
          display_name: string;
          fat_g?: number;
          fiber_g?: number | null;
          food_id?: string | null;
          food_source: string;
          grams: number;
          id?: string;
          kcal?: number;
          meal_id: string;
          micros?: NonNullable<Json>;
          per100g: NonNullable<Json>;
          position?: number;
          protein_g?: number;
          sat_fat_g?: number | null;
          serving_qty?: number | null;
          serving_unit?: string | null;
          sodium_mg?: number | null;
          sugar_g?: number | null;
          updated_at?: string;
          user_edited?: boolean;
          user_id: string;
        };
        Update: {
          ai_confidence?: number | null;
          carbs_g?: number;
          cooking_method?: string | null;
          created_at?: string;
          display_name?: string;
          fat_g?: number;
          fiber_g?: number | null;
          food_id?: string | null;
          food_source?: string;
          grams?: number;
          id?: string;
          kcal?: number;
          meal_id?: string;
          micros?: NonNullable<Json>;
          per100g?: NonNullable<Json>;
          position?: number;
          protein_g?: number;
          sat_fat_g?: number | null;
          serving_qty?: number | null;
          serving_unit?: string | null;
          sodium_mg?: number | null;
          sugar_g?: number | null;
          updated_at?: string;
          user_edited?: boolean;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'meal_items_meal_id_fkey';
            columns: ['meal_id'];
            isOneToOne: false;
            referencedRelation: 'meals';
            referencedColumns: ['id'];
          },
        ];
      };
      meals: {
        Row: {
          ai_scan_id: string | null;
          carbs_g: number;
          created_at: string;
          deleted_at: string | null;
          eaten_at: string;
          fat_g: number;
          fiber_g: number;
          id: string;
          kcal: number;
          local_date: string;
          meal_type: string;
          note: string | null;
          photo_path: string | null;
          protein_g: number;
          sat_fat_g: number;
          sodium_mg: number;
          source: string;
          sugar_g: number;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          ai_scan_id?: string | null;
          carbs_g?: number;
          created_at?: string;
          deleted_at?: string | null;
          eaten_at: string;
          fat_g?: number;
          fiber_g?: number;
          id?: string;
          kcal?: number;
          local_date: string;
          meal_type: string;
          note?: string | null;
          photo_path?: string | null;
          protein_g?: number;
          sat_fat_g?: number;
          sodium_mg?: number;
          source: string;
          sugar_g?: number;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          ai_scan_id?: string | null;
          carbs_g?: number;
          created_at?: string;
          deleted_at?: string | null;
          eaten_at?: string;
          fat_g?: number;
          fiber_g?: number;
          id?: string;
          kcal?: number;
          local_date?: string;
          meal_type?: string;
          note?: string | null;
          photo_path?: string | null;
          protein_g?: number;
          sat_fat_g?: number;
          sodium_mg?: number;
          source?: string;
          sugar_g?: number;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      notification_settings: {
        Row: {
          meal_reminders: NonNullable<Json>;
          smart_reminders: boolean;
          updated_at: string;
          user_id: string;
          water_reminder: NonNullable<Json>;
          weekly_summary: boolean;
          weigh_in_reminder: NonNullable<Json>;
        };
        Insert: {
          meal_reminders?: NonNullable<Json>;
          smart_reminders?: boolean;
          updated_at?: string;
          user_id: string;
          water_reminder?: NonNullable<Json>;
          weekly_summary?: boolean;
          weigh_in_reminder?: NonNullable<Json>;
        };
        Update: {
          meal_reminders?: NonNullable<Json>;
          smart_reminders?: boolean;
          updated_at?: string;
          user_id?: string;
          water_reminder?: NonNullable<Json>;
          weekly_summary?: boolean;
          weigh_in_reminder?: NonNullable<Json>;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          activity_level: string | null;
          allergies: string[];
          analytics_consent: boolean;
          birth_date: string | null;
          country: string | null;
          created_at: string;
          dietary_preferences: string[];
          display_name: string | null;
          goal_type: string | null;
          height_cm: number | null;
          id: string;
          locale: string;
          onboarding_completed: boolean;
          save_photos: boolean;
          sex: string | null;
          target_weight_kg: number | null;
          terms_accepted_at: string | null;
          terms_version: string | null;
          timezone: string;
          unit_system: string;
          updated_at: string;
          weekly_rate_kg: number | null;
        };
        Insert: {
          activity_level?: string | null;
          allergies?: string[];
          analytics_consent?: boolean;
          birth_date?: string | null;
          country?: string | null;
          created_at?: string;
          dietary_preferences?: string[];
          display_name?: string | null;
          goal_type?: string | null;
          height_cm?: number | null;
          id: string;
          locale?: string;
          onboarding_completed?: boolean;
          save_photos?: boolean;
          sex?: string | null;
          target_weight_kg?: number | null;
          terms_accepted_at?: string | null;
          terms_version?: string | null;
          timezone?: string;
          unit_system?: string;
          updated_at?: string;
          weekly_rate_kg?: number | null;
        };
        Update: {
          activity_level?: string | null;
          allergies?: string[];
          analytics_consent?: boolean;
          birth_date?: string | null;
          country?: string | null;
          created_at?: string;
          dietary_preferences?: string[];
          display_name?: string | null;
          goal_type?: string | null;
          height_cm?: number | null;
          id?: string;
          locale?: string;
          onboarding_completed?: boolean;
          save_photos?: boolean;
          sex?: string | null;
          target_weight_kg?: number | null;
          terms_accepted_at?: string | null;
          terms_version?: string | null;
          timezone?: string;
          unit_system?: string;
          updated_at?: string;
          weekly_rate_kg?: number | null;
        };
        Relationships: [];
      };
      rate_limits: {
        Row: {
          bucket: string;
          hits: number;
          window_start: string;
        };
        Insert: {
          bucket: string;
          hits?: number;
          window_start: string;
        };
        Update: {
          bucket?: string;
          hits?: number;
          window_start?: string;
        };
        Relationships: [];
      };
      recent_foods: {
        Row: {
          display_name: string;
          food_id: string | null;
          food_key: string;
          food_source: string;
          last_grams: number;
          last_used_at: string;
          per100g: NonNullable<Json>;
          use_count: number;
          user_id: string;
        };
        Insert: {
          display_name: string;
          food_id?: string | null;
          food_key: string;
          food_source: string;
          last_grams: number;
          last_used_at?: string;
          per100g: NonNullable<Json>;
          use_count?: number;
          user_id: string;
        };
        Update: {
          display_name?: string;
          food_id?: string | null;
          food_key?: string;
          food_source?: string;
          last_grams?: number;
          last_used_at?: string;
          per100g?: NonNullable<Json>;
          use_count?: number;
          user_id?: string;
        };
        Relationships: [];
      };
      recipe_items: {
        Row: {
          display_name: string;
          food_id: string | null;
          food_source: string;
          grams: number;
          id: string;
          per100g: NonNullable<Json>;
          position: number;
          recipe_id: string;
          user_id: string;
        };
        Insert: {
          display_name: string;
          food_id?: string | null;
          food_source: string;
          grams: number;
          id?: string;
          per100g: NonNullable<Json>;
          position?: number;
          recipe_id: string;
          user_id: string;
        };
        Update: {
          display_name?: string;
          food_id?: string | null;
          food_source?: string;
          grams?: number;
          id?: string;
          per100g?: NonNullable<Json>;
          position?: number;
          recipe_id?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'recipe_items_recipe_id_fkey';
            columns: ['recipe_id'];
            isOneToOne: false;
            referencedRelation: 'recipes';
            referencedColumns: ['id'];
          },
        ];
      };
      recipes: {
        Row: {
          carbs_g: number;
          created_at: string;
          deleted_at: string | null;
          fat_g: number;
          fiber_g: number;
          id: string;
          items: NonNullable<Json>;
          kcal: number;
          name: string;
          note: string | null;
          protein_g: number;
          servings: number;
          total_grams: number;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          carbs_g?: number;
          created_at?: string;
          deleted_at?: string | null;
          fat_g?: number;
          fiber_g?: number;
          id?: string;
          items?: NonNullable<Json>;
          kcal?: number;
          name: string;
          note?: string | null;
          protein_g?: number;
          servings?: number;
          total_grams?: number;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          carbs_g?: number;
          created_at?: string;
          deleted_at?: string | null;
          fat_g?: number;
          fiber_g?: number;
          id?: string;
          items?: NonNullable<Json>;
          kcal?: number;
          name?: string;
          note?: string | null;
          protein_g?: number;
          servings?: number;
          total_grams?: number;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      revenuecat_events: {
        Row: {
          app_user_id: string | null;
          id: string;
          payload: NonNullable<Json>;
          received_at: string;
          type: string;
        };
        Insert: {
          app_user_id?: string | null;
          id: string;
          payload: NonNullable<Json>;
          received_at?: string;
          type: string;
        };
        Update: {
          app_user_id?: string | null;
          id?: string;
          payload?: NonNullable<Json>;
          received_at?: string;
          type?: string;
        };
        Relationships: [];
      };
      streaks: {
        Row: {
          current_streak: number;
          last_logged_date: string | null;
          longest_streak: number;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          current_streak?: number;
          last_logged_date?: string | null;
          longest_streak?: number;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          current_streak?: number;
          last_logged_date?: string | null;
          longest_streak?: number;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      subscriptions: {
        Row: {
          created_at: string;
          entitlement: string;
          environment: string | null;
          expires_at: string | null;
          is_trial: boolean;
          last_event_at: string | null;
          last_event_type: string | null;
          original_transaction_id: string | null;
          platform: string | null;
          product_id: string | null;
          status: string;
          updated_at: string;
          updated_by_webhook_at: string | null;
          user_id: string;
          will_renew: boolean;
        };
        Insert: {
          created_at?: string;
          entitlement?: string;
          environment?: string | null;
          expires_at?: string | null;
          is_trial?: boolean;
          last_event_at?: string | null;
          last_event_type?: string | null;
          original_transaction_id?: string | null;
          platform?: string | null;
          product_id?: string | null;
          status: string;
          updated_at?: string;
          updated_by_webhook_at?: string | null;
          user_id: string;
          will_renew?: boolean;
        };
        Update: {
          created_at?: string;
          entitlement?: string;
          environment?: string | null;
          expires_at?: string | null;
          is_trial?: boolean;
          last_event_at?: string | null;
          last_event_type?: string | null;
          original_transaction_id?: string | null;
          platform?: string | null;
          product_id?: string | null;
          status?: string;
          updated_at?: string;
          updated_by_webhook_at?: string | null;
          user_id?: string;
          will_renew?: boolean;
        };
        Relationships: [];
      };
      usage_quotas: {
        Row: {
          coach_messages: number;
          day: string;
          photo_scans: number;
          text_queries: number;
          user_id: string;
        };
        Insert: {
          coach_messages?: number;
          day: string;
          photo_scans?: number;
          text_queries?: number;
          user_id: string;
        };
        Update: {
          coach_messages?: number;
          day?: string;
          photo_scans?: number;
          text_queries?: number;
          user_id?: string;
        };
        Relationships: [];
      };
      user_credits: {
        Row: {
          bonus_photo_scans: number;
          lifetime_coach_messages: number;
          lifetime_photo_scans: number;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          bonus_photo_scans?: number;
          lifetime_coach_messages?: number;
          lifetime_photo_scans?: number;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          bonus_photo_scans?: number;
          lifetime_coach_messages?: number;
          lifetime_photo_scans?: number;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      water_logs: {
        Row: {
          created_at: string;
          deleted_at: string | null;
          id: string;
          local_date: string;
          logged_at: string;
          ml: number;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          deleted_at?: string | null;
          id?: string;
          local_date: string;
          logged_at: string;
          ml: number;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          deleted_at?: string | null;
          id?: string;
          local_date?: string;
          logged_at?: string;
          ml?: number;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      weight_logs: {
        Row: {
          created_at: string;
          deleted_at: string | null;
          id: string;
          local_date: string;
          logged_at: string;
          source: string;
          updated_at: string;
          user_id: string;
          weight_kg: number;
        };
        Insert: {
          created_at?: string;
          deleted_at?: string | null;
          id?: string;
          local_date: string;
          logged_at: string;
          source?: string;
          updated_at?: string;
          user_id: string;
          weight_kg: number;
        };
        Update: {
          created_at?: string;
          deleted_at?: string | null;
          id?: string;
          local_date?: string;
          logged_at?: string;
          source?: string;
          updated_at?: string;
          user_id?: string;
          weight_kg?: number;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      ai_cost_today: { Args: Record<PropertyKey, never>; Returns: number };
      check_rate_limit: {
        Args: { p_bucket: string; p_max: number; p_window_seconds: number };
        Returns: boolean;
      };
      consume_quota: {
        Args: {
          p_daily_limit: number;
          p_day: string;
          p_kind: string;
          p_trial_limit?: number;
          p_user: string;
        };
        Returns: {
          allowed: boolean;
          bucket: string;
          used: number;
        }[];
      };
      f_unaccent: { Args: { '': string }; Returns: string };
      my_plan: { Args: Record<PropertyKey, never>; Returns: string };
      plan_for: { Args: { p_user: string }; Returns: string };
      refund_quota: {
        Args: { p_bucket: string; p_day: string; p_kind: string; p_user: string };
        Returns: undefined;
      };
      search_regional_foods: {
        Args: { lim?: number; q: string };
        Returns: {
          aliases: string[];
          carbs_g: number;
          category: string;
          countries: string[];
          created_at: string;
          fat_g: number;
          fiber_g: number | null;
          id: string;
          kcal: number;
          micros: NonNullable<Json>;
          name_en: string;
          name_es: string;
          name_pt: string;
          protein_g: number;
          sat_fat_g: number | null;
          servings: NonNullable<Json>;
          sodium_mg: number | null;
          source: string;
          sugar_g: number | null;
        }[];
        SetofOptions: {
          from: '*';
          to: 'foods_regional';
          isOneToOne: false;
          isSetofReturn: true;
        };
      };
      upsert_meal: { Args: { p: Json }; Returns: string };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] & DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    keyof DefaultSchema['Enums'] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    keyof DefaultSchema['CompositeTypes'] | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {},
  },
} as const;
