// GENERATED by scripts/sync-shared.mjs from packages/shared/src — do not edit.
import { z } from 'zod';
import { CookingMethodSchema, LocaleSchema, MealTypeSchema } from './enums.ts';

/**
 * Structured output contract for the vision/text models. The same Zod schema produces the JSON
 * schema sent as the tool definition (see `aiAnalysisJsonSchema`) and validates the response.
 */
export const AiPer100gSchema = z.object({
  kcal: z.number().min(0).max(950),
  protein_g: z.number().min(0).max(100),
  carbs_g: z.number().min(0).max(100),
  fat_g: z.number().min(0).max(100),
  fiber_g: z.number().min(0).max(100).optional(),
  sugar_g: z.number().min(0).max(100).optional(),
  sodium_mg: z.number().min(0).max(40000).optional(),
  sat_fat_g: z.number().min(0).max(100).optional(),
});

export const AiItemSchema = z.object({
  name: z.string().min(1).max(120).describe('Food name in the user language, using local names'),
  name_en: z.string().min(1).max(120).describe('English name used for database lookup'),
  estimated_grams: z.number().min(0).max(3000),
  household_measure: z.string().max(60).describe('e.g. "1 unidad mediana", "1 taza"'),
  cooking_method: CookingMethodSchema,
  confidence: z.number().min(0).max(1),
  per_100g_estimate: AiPer100gSchema,
  search_hints: z.array(z.string().max(80)).max(5),
  bbox: z
    .object({
      x: z.number().min(0).max(1),
      y: z.number().min(0).max(1),
      w: z.number().min(0).max(1),
      h: z.number().min(0).max(1),
    })
    .optional()
    .describe('Approximate normalized bounding box of the item in the image'),
});
export type AiItem = z.infer<typeof AiItemSchema>;

export const AiAnalysisSchema = z.object({
  is_food: z.boolean(),
  dish_name: z.string().max(120).nullable(),
  items: z.array(AiItemSchema).max(20),
  hidden_ingredients_question: z.string().max(200).nullable(),
  notes: z.string().max(400).nullable(),
});
export type AiAnalysis = z.infer<typeof AiAnalysisSchema>;

/** Nutrition label (OCR) structured output. */
export const AiLabelSchema = z.object({
  is_label: z.boolean(),
  product_name: z.string().max(120).nullable(),
  brand: z.string().max(80).nullable(),
  serving_size_g: z.number().min(0).max(2000).nullable(),
  per_100g: AiPer100gSchema.nullable(),
  per_serving: AiPer100gSchema.nullable(),
  notes: z.string().max(300).nullable(),
});
export type AiLabel = z.infer<typeof AiLabelSchema>;

export function aiAnalysisJsonSchema(): Record<string, unknown> {
  return z.toJSONSchema(AiAnalysisSchema, { target: 'draft-7' }) as Record<string, unknown>;
}
export function aiLabelJsonSchema(): Record<string, unknown> {
  return z.toJSONSchema(AiLabelSchema, { target: 'draft-7' }) as Record<string, unknown>;
}

// ---- Edge Function request / response contracts ----

export const AnalyzeMealRequestSchema = z.object({
  /** Path inside the private `meal-photos` bucket: `<user_id>/<uuid>.jpg`. */
  photo_path: z.string().min(3).max(300),
  image_sha256: z.string().regex(/^[a-f0-9]{64}$/),
  locale: LocaleSchema.default('es-AR'),
  meal_type: MealTypeSchema.optional(),
  mode: z.enum(['meal', 'label']).default('meal'),
  /** false → the server deletes the photo right after analysis (user privacy setting). */
  keep_photo: z.boolean().default(true),
});
export type AnalyzeMealRequest = z.infer<typeof AnalyzeMealRequestSchema>;

export const AnalyzeTextRequestSchema = z.object({
  text: z.string().trim().min(2).max(500),
  locale: LocaleSchema.default('es-AR'),
  source: z.enum(['text', 'voice', 'recipe']).default('text'),
});
export type AnalyzeTextRequest = z.infer<typeof AnalyzeTextRequestSchema>;

export const EnrichedItemSchema = z.object({
  display_name: z.string(),
  name_en: z.string(),
  grams: z.number(),
  household_measure: z.string(),
  cooking_method: CookingMethodSchema,
  confidence: z.number(),
  food_source: z.enum(['regional', 'usda', 'ai', 'off', 'custom']),
  food_id: z.string().nullable(),
  per100g: AiPer100gSchema,
  bbox: AiItemSchema.shape.bbox,
});
export type EnrichedItem = z.infer<typeof EnrichedItemSchema>;

export const AnalyzeResponseSchema = z.object({
  scan_id: z.string().uuid().nullable(),
  cached: z.boolean(),
  is_food: z.boolean(),
  dish_name: z.string().nullable(),
  items: z.array(EnrichedItemSchema),
  hidden_ingredients_question: z.string().nullable(),
  notes: z.string().nullable(),
  model: z.string(),
  quota: z.object({ used: z.number(), limit: z.number(), remaining: z.number() }),
});
export type AnalyzeResponse = z.infer<typeof AnalyzeResponseSchema>;

export const CoachMessageSchema = z.object({
  role: z.enum(['user', 'assistant']),
  content: z.string().max(4000),
});
export const CoachRequestSchema = z.object({
  messages: z.array(CoachMessageSchema).min(1).max(30),
  locale: LocaleSchema.default('es-AR'),
  /** Optional photo (premium): fridge → recipe ideas, menu → best choices for the user's goals. */
  photo_path: z.string().min(3).max(300).optional(),
  photo_kind: z.enum(['fridge', 'menu']).optional(),
});

export const CoachResponseSchema = z.object({
  reply: z.string(),
  quota: z.object({ used: z.number(), limit: z.number(), remaining: z.number() }),
});
export type CoachResponse = z.infer<typeof CoachResponseSchema>;

export const LabelResponseSchema = z.object({
  scan_id: z.string().uuid().nullable(),
  label: AiLabelSchema,
  quota: z.object({ used: z.number(), limit: z.number(), remaining: z.number() }),
});
export type LabelResponse = z.infer<typeof LabelResponseSchema>;

export const MealPlanRequestSchema = z.object({
  locale: LocaleSchema.default('es-AR'),
  budget: z.enum(['low', 'mid', 'high']).default('mid'),
  days: z.number().int().min(1).max(7).default(7),
});

export const MealPlanSchema = z.object({
  days: z
    .array(
      z.object({
        day: z.number().int(),
        meals: z.array(
          z.object({
            meal_type: MealTypeSchema,
            name: z.string().max(120),
            description: z.string().max(300),
            kcal: z.number(),
            protein_g: z.number(),
            carbs_g: z.number(),
            fat_g: z.number(),
          }),
        ),
      }),
    )
    .max(7),
  shopping_list: z.array(z.object({ item: z.string().max(80), quantity: z.string().max(40), category: z.string().max(40) })),
  notes: z.string().max(400).nullable(),
});
export type MealPlan = z.infer<typeof MealPlanSchema>;

export const QuotaStatusSchema = z.object({
  plan: z.enum(['free', 'premium']),
  day: z.string(),
  photo_scan: z.object({ used: z.number(), limit: z.number(), remaining: z.number() }),
  text_query: z.object({ used: z.number(), limit: z.number(), remaining: z.number() }),
  coach_message: z.object({ used: z.number(), limit: z.number(), remaining: z.number() }),
  bonus_photo_scans: z.number(),
  coach_trial_remaining: z.number(),
});
export type QuotaStatus = z.infer<typeof QuotaStatusSchema>;
export type CoachRequest = z.infer<typeof CoachRequestSchema>;

export const ApiErrorCodeSchema = z.enum([
  'UNAUTHORIZED',
  'INVALID_INPUT',
  'QUOTA_EXCEEDED',
  'PREMIUM_REQUIRED',
  'RATE_LIMITED',
  'NOT_FOOD',
  'AI_TIMEOUT',
  'AI_INVALID_RESPONSE',
  'BUDGET_EXCEEDED',
  'NOT_FOUND',
  'INTERNAL',
]);
export type ApiErrorCode = z.infer<typeof ApiErrorCodeSchema>;
