#!/usr/bin/env python3
"""Generates packages/shared/data/foods-regional.json and supabase/seed/01_foods_regional.sql."""
import json, os, sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'data'))
from foods_regional_source import F, SOURCES  # noqa: E402

root = os.path.join(os.path.dirname(__file__), '..')
ids = set(); out = []
for row in F:
    (fid, es, en, pt, cat, kcal, p, c, f, fib, sug, na, sat, servings, src, aliases) = row
    assert fid not in ids, fid; ids.add(fid)
    # sanity: energy from macros within 25% (alcohol/fiber explain the rest)
    calc = p*4 + c*4 + f*9
    if kcal > 30 and abs(calc - kcal) / kcal > 0.25 and cat != 'bebidas':
        print(f'warning: {fid} kcal {kcal} vs macros {calc:.0f}', file=sys.stderr)
    out.append({
        'id': fid, 'name_es': es, 'name_en': en, 'name_pt': pt, 'aliases': aliases, 'category': cat,
        'kcal': kcal, 'protein_g': p, 'carbs_g': c, 'fat_g': f, 'fiber_g': fib, 'sugar_g': sug,
        'sodium_mg': na, 'sat_fat_g': sat,
        'servings': [{'unit': u, 'grams': g} for (u, g) in servings],
        'source': SOURCES[src],
    })

data_path = os.path.join(root, 'packages/shared/data/foods-regional.json')
with open(data_path, 'w') as fh:
    json.dump(out, fh, ensure_ascii=False, indent=1); fh.write('\n')

def q(s): return "'" + str(s).replace("'", "''") + "'"
def arr(a): return "array[" + ",".join(q(x) for x in a) + "]::text[]" if a else "'{}'::text[]"
lines = ['-- GENERATED by scripts/gen-foods.py — do not edit. Values per 100 g.',
         'insert into public.foods_regional (id, name_es, name_en, name_pt, aliases, category, kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg, sat_fat_g, servings, source) values']
vals = []
for o in out:
    vals.append('(' + ', '.join([q(o['id']), q(o['name_es']), q(o['name_en']), q(o['name_pt']), arr(o['aliases']), q(o['category']),
        str(o['kcal']), str(o['protein_g']), str(o['carbs_g']), str(o['fat_g']), str(o['fiber_g']), str(o['sugar_g']), str(o['sodium_mg']), str(o['sat_fat_g']),
        q(json.dumps(o['servings'])) + '::jsonb', q(o['source'])]) + ')')
lines.append(',\n'.join(vals))
lines.append('on conflict (id) do update set name_es = excluded.name_es, name_en = excluded.name_en, name_pt = excluded.name_pt, aliases = excluded.aliases, category = excluded.category, kcal = excluded.kcal, protein_g = excluded.protein_g, carbs_g = excluded.carbs_g, fat_g = excluded.fat_g, fiber_g = excluded.fiber_g, sugar_g = excluded.sugar_g, sodium_mg = excluded.sodium_mg, sat_fat_g = excluded.sat_fat_g, servings = excluded.servings, source = excluded.source;')
os.makedirs(os.path.join(root, 'supabase/seed'), exist_ok=True)
with open(os.path.join(root, 'supabase/seed/01_foods_regional.sql'), 'w') as fh:
    fh.write('\n'.join(lines) + '\n')
print(f'{len(out)} foods written')
