#!/usr/bin/env node
/**
 * Copies packages/shared/src into supabase/functions/_shared/shared so Edge Functions (Deno)
 * can import the same plans, schemas and formulas as the app. Run with --check in CI.
 */
import { createHash } from 'node:crypto';
import { mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = join(root, 'packages/shared/src');
const dest = join(root, 'supabase/functions/_shared/shared');
const HEADER = '// GENERATED by scripts/sync-shared.mjs from packages/shared/src — do not edit.\n';
const check = process.argv.includes('--check');

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const p = join(dir, name);
    return statSync(p).isDirectory() ? walk(p) : [p];
  });
}

const expected = new Map(
  walk(src)
    .filter((f) => f.endsWith('.ts'))
    .map((f) => [relative(src, f), HEADER + readFileSync(f, 'utf8')]),
);

if (check) {
  const actual = new Map();
  try {
    for (const f of walk(dest)) actual.set(relative(dest, f), readFileSync(f, 'utf8'));
  } catch {
    // dest missing
  }
  const hash = (m) =>
    createHash('sha256')
      .update(JSON.stringify([...m.entries()].sort()))
      .digest('hex');
  if (hash(expected) !== hash(actual)) {
    console.error('✖ supabase/functions/_shared/shared is out of sync. Run `pnpm sync:shared`.');
    process.exit(1);
  }
  console.log('✔ shared code in sync');
} else {
  rmSync(dest, { recursive: true, force: true });
  for (const [rel, content] of expected) {
    const out = join(dest, rel);
    mkdirSync(dirname(out), { recursive: true });
    writeFileSync(out, content);
  }
  console.log(`✔ synced ${expected.size} files to ${relative(root, dest)}`);
}
