// GENERATED by scripts/sync-shared.mjs from packages/shared/src — do not edit.
import type { GoalType, MealSource, MealType } from './schemas/enums.ts';

/**
 * Achievement catalog, built from metrics × tiers (~120 achievements). Titles/descriptions live in
 * i18n under `achievements.metrics.<metric>` and take `{{count}}`.
 *
 * Health note: weight achievements count progress *towards the user's own goal* (safeguarded by
 * computeGoalPlan); there is no achievement for eating less or for fast weight loss.
 */
export const ACHIEVEMENT_CATEGORIES = [
  'consistency',
  'logging',
  'nutrition',
  'body',
  'kitchen',
  'exploration',
] as const;
export type AchievementCategory = (typeof ACHIEVEMENT_CATEGORIES)[number];

export const ACHIEVEMENT_METRICS = {
  // consistency
  longestStreak: {
    category: 'consistency',
    icon: 'flame',
    tiers: [3, 5, 7, 14, 21, 30, 45, 60, 90, 120, 180, 365],
  },
  loggedDays: { category: 'consistency', icon: 'calendar', tiers: [7, 14, 30, 60, 100, 200, 365] },
  fullDays: { category: 'consistency', icon: 'checkmark-done', tiers: [1, 7, 30, 100] },
  weekendDays: { category: 'consistency', icon: 'sunny', tiers: [4, 10, 25, 50] },
  breakfastDays: { category: 'consistency', icon: 'cafe', tiers: [7, 30, 100] },
  // logging
  mealsLogged: {
    category: 'logging',
    icon: 'restaurant',
    tiers: [1, 10, 25, 50, 100, 250, 500, 1000, 2000],
  },
  photoScans: { category: 'logging', icon: 'camera', tiers: [1, 5, 10, 25, 50, 100, 250, 500] },
  textLogs: { category: 'logging', icon: 'mic', tiers: [1, 10, 25, 50, 100] },
  barcodeScans: { category: 'logging', icon: 'barcode', tiers: [1, 10, 25, 50, 100] },
  corrections: { category: 'logging', icon: 'create', tiers: [1, 10, 50] },
  // nutrition
  proteinDays: { category: 'nutrition', icon: 'barbell', tiers: [1, 3, 7, 14, 30, 60, 100] },
  waterDays: { category: 'nutrition', icon: 'water', tiers: [1, 3, 7, 14, 30, 60, 100] },
  calorieRangeDays: { category: 'nutrition', icon: 'flag', tiers: [1, 3, 7, 14, 30, 60, 100] },
  fiberDays: { category: 'nutrition', icon: 'leaf', tiers: [1, 7, 30] },
  // body
  weighIns: { category: 'body', icon: 'scale', tiers: [1, 5, 10, 25, 50, 100] },
  goalProgressKg: { category: 'body', icon: 'trending-up', tiers: [1, 2, 3, 5, 7, 10, 15, 20] },
  goalReached: { category: 'body', icon: 'trophy', tiers: [1] },
  measurements: { category: 'body', icon: 'resize', tiers: [1, 5, 10] },
  // kitchen
  recipes: { category: 'kitchen', icon: 'book', tiers: [1, 3, 5, 10, 25] },
  customFoods: { category: 'kitchen', icon: 'add-circle', tiers: [1, 5, 10, 25] },
  favorites: { category: 'kitchen', icon: 'star', tiers: [1, 5, 10, 25] },
  // exploration
  uniqueFoods: { category: 'exploration', icon: 'grid', tiers: [10, 25, 50, 100, 200, 500] },
} as const satisfies Record<
  string,
  { category: AchievementCategory; icon: string; tiers: readonly number[] }
>;

export type AchievementMetric = keyof typeof ACHIEVEMENT_METRICS;
export type AchievementStats = Record<AchievementMetric, number>;

/** Ids kept from the first catalog so achievements users already unlocked stay unlocked. */
const LEGACY_IDS: Partial<Record<`${AchievementMetric}_${number}`, string>> = {
  mealsLogged_1: 'first_meal',
  mealsLogged_50: 'meals_50',
  photoScans_1: 'first_scan',
  longestStreak_3: 'streak_3',
  longestStreak_7: 'streak_7',
  longestStreak_30: 'streak_30',
  proteinDays_1: 'protein_goal',
  waterDays_1: 'water_goal',
  weighIns_1: 'first_weigh_in',
  recipes_1: 'first_recipe',
};

export interface Achievement {
  id: string;
  metric: AchievementMetric;
  threshold: number;
  category: AchievementCategory;
  icon: string;
  /** 1-based tier within its metric (1 = easiest). */
  tier: number;
}

export const ACHIEVEMENTS: readonly Achievement[] = (
  Object.entries(ACHIEVEMENT_METRICS) as [
    AchievementMetric,
    (typeof ACHIEVEMENT_METRICS)[AchievementMetric],
  ][]
).flatMap(([metric, def]) =>
  def.tiers.map((threshold, i) => ({
    id: LEGACY_IDS[`${metric}_${threshold}`] ?? `${metric}_${threshold}`,
    metric,
    threshold,
    category: def.category,
    icon: def.icon,
    tier: i + 1,
  })),
);

export type AchievementId = string;

/** Returns newly unlocked achievement ids (not present in `alreadyUnlocked`). */
export function evaluateAchievements(
  stats: AchievementStats,
  alreadyUnlocked: ReadonlySet<string>,
): AchievementId[] {
  return ACHIEVEMENTS.filter(
    (a) => !alreadyUnlocked.has(a.id) && (stats[a.metric] ?? 0) >= a.threshold,
  ).map((a) => a.id);
}

/** 0..1 progress towards an achievement. */
export function achievementProgress(a: Achievement, stats: Partial<AchievementStats>): number {
  return Math.max(0, Math.min(1, (stats[a.metric] ?? 0) / a.threshold));
}

// ── Stats ───────────────────────────────────────────────────────────────────

export interface AchievementInput {
  meals: readonly {
    local_date: string;
    meal_type: MealType;
    source: MealSource;
    totals: { kcal: number; protein_g: number; fiber_g?: number | null };
    items: readonly { display_name: string; user_edited?: boolean | null }[];
  }[];
  /** Water per local date (ml). */
  waterByDate: ReadonlyMap<string, number>;
  /** Weigh-ins, any order. */
  weights: readonly { local_date: string; weight_kg: number }[];
  /** Daily targets in effect on a given date. */
  goalFor: (date: string) => {
    kcal: number;
    protein_g: number;
    fiber_g: number | null;
    water_ml: number | null;
  };
  goalType: GoalType | null;
  targetWeightKg: number | null;
  longestStreak: number;
  counts: { measurements: number; recipes: number; customFoods: number; favorites: number };
}

/** Tolerance for "within your calorie range" days. */
export const CALORIE_RANGE_TOLERANCE = 0.1;

const isWeekend = (date: string) => {
  const d = new Date(`${date}T12:00:00Z`).getUTCDay();
  return d === 0 || d === 6;
};

export function computeAchievementStats(input: AchievementInput): AchievementStats {
  const byDate = new Map<string, AchievementInput['meals'][number][]>();
  for (const m of input.meals) {
    const list = byDate.get(m.local_date);
    if (list) list.push(m);
    else byDate.set(m.local_date, [m]);
  }
  let fullDays = 0;
  let weekendDays = 0;
  let breakfastDays = 0;
  let proteinDays = 0;
  let calorieRangeDays = 0;
  let fiberDays = 0;
  for (const [date, meals] of byDate) {
    const types = new Set(meals.map((m) => m.meal_type));
    if (types.has('breakfast') && types.has('lunch') && types.has('dinner')) fullDays++;
    if (types.has('breakfast')) breakfastDays++;
    if (isWeekend(date)) weekendDays++;
    const goal = input.goalFor(date);
    const kcal = meals.reduce((s, m) => s + m.totals.kcal, 0);
    const protein = meals.reduce((s, m) => s + m.totals.protein_g, 0);
    const fiber = meals.reduce((s, m) => s + (m.totals.fiber_g ?? 0), 0);
    if (goal.protein_g > 0 && protein >= goal.protein_g) proteinDays++;
    if (goal.kcal > 0 && Math.abs(kcal - goal.kcal) <= goal.kcal * CALORIE_RANGE_TOLERANCE)
      calorieRangeDays++;
    if (goal.fiber_g && fiber >= goal.fiber_g) fiberDays++;
  }
  let waterDays = 0;
  for (const [date, ml] of input.waterByDate) {
    const target = input.goalFor(date).water_ml;
    if (target && ml >= target) waterDays++;
  }

  const weights = [...input.weights].sort((a, b) => a.local_date.localeCompare(b.local_date));
  const first = weights[0]?.weight_kg;
  const last = weights[weights.length - 1]?.weight_kg;
  const direction =
    input.goalType === 'lose'
      ? 1
      : input.goalType === 'gain' || input.goalType === 'build_muscle'
        ? -1
        : 0;
  const goalProgressKg =
    first != null && last != null && direction !== 0
      ? Math.max(0, Math.floor((first - last) * direction))
      : 0;
  const target = input.targetWeightKg;
  const goalReached =
    weights.length >= 2 &&
    target != null &&
    first != null &&
    last != null &&
    direction !== 0 &&
    (first - target) * direction > 0 &&
    (last - target) * direction <= 0
      ? 1
      : 0;

  const uniqueFoods = new Set(
    input.meals.flatMap((m) => m.items.map((i) => i.display_name.trim().toLowerCase())),
  ).size;

  return {
    longestStreak: input.longestStreak,
    loggedDays: byDate.size,
    fullDays,
    weekendDays,
    breakfastDays,
    mealsLogged: input.meals.length,
    photoScans: input.meals.filter((m) => m.source === 'photo' || m.source === 'label').length,
    textLogs: input.meals.filter((m) => m.source === 'text' || m.source === 'voice').length,
    barcodeScans: input.meals.filter((m) => m.source === 'barcode').length,
    corrections: input.meals.reduce((s, m) => s + m.items.filter((i) => i.user_edited).length, 0),
    proteinDays,
    waterDays,
    calorieRangeDays,
    fiberDays,
    weighIns: weights.length,
    goalProgressKg,
    goalReached,
    measurements: input.counts.measurements,
    recipes: input.counts.recipes,
    customFoods: input.counts.customFoods,
    favorites: input.counts.favorites,
    uniqueFoods,
  };
}
