// GENERATED by scripts/sync-shared.mjs from packages/shared/src — do not edit.
export const LB_PER_KG = 2.2046226218;
export const CM_PER_IN = 2.54;
export const ML_PER_FL_OZ = 29.5735295625;
export const G_PER_OZ = 28.349523125;

export const kgToLb = (kg: number) => kg * LB_PER_KG;
export const lbToKg = (lb: number) => lb / LB_PER_KG;
export const gToOz = (g: number) => g / G_PER_OZ;
export const ozToG = (oz: number) => oz * G_PER_OZ;
export const mlToFlOz = (ml: number) => ml / ML_PER_FL_OZ;
export const flOzToMl = (oz: number) => oz * ML_PER_FL_OZ;

export function cmToFtIn(cm: number): { ft: number; inches: number } {
  const totalIn = cm / CM_PER_IN;
  let ft = Math.floor(totalIn / 12);
  let inches = Math.round(totalIn - ft * 12);
  if (inches === 12) {
    ft += 1;
    inches = 0;
  }
  return { ft, inches };
}

export function ftInToCm(ft: number, inches: number): number {
  return (ft * 12 + inches) * CM_PER_IN;
}

export const kcalToKj = (kcal: number) => kcal * 4.184;
export const kjToKcal = (kj: number) => kj / 4.184;
